---
apiVersion: v1
kind: Template
labels:
  application: httpd-blue-green-pipeline
metadata:
  name: httpd-blue-green-pipeline
objects:
  -
    apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        build: httpd-blue-green-pipeline
      name: httpd-blue-green-pipeline
    spec:
      runPolicy: Serial
      source: {}
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfile: |-
              try {
                 timeout(time: 15, unit: 'MINUTES') {
                    def project = ""
                        def gitURL = "${GIT_REPO_URL}"
                        def gitBranch = "${GIT_REPO_BRANCH}"
                        def gitCommit = "${GIT_COMMIT}"
                        def gitContext = "${GIT_CONTEXT_DIR}"
                        def microName = "${MICROSERVICE_NAME}"
                        def appBlueName = "${APPLICATION_BLUE_NAME}"
                        def appGreenName = "${APPLICATION_GREEN_NAME}"
                        def appID = "${APPLICATION_ID}"
                        def appRoute = "${APPLICATION_ROUTE}"
                        def cpuRequest = "${CPU_REQUEST}"
                        def cpuLimit = "${CPU_LIMIT}"
                        def memRequest = "${MEM_REQUEST}"
                        def memLimit = "${MEM_LIMIT}"
                        def replicas = "${NUM_REPLICAS}"
                        def version = "${VERSION_NUMBER}"
                    node {
                      project = "${env.PROJECT_NAME}"

                      stage('Create Blue-App BuildConfig') {
                        sh "oc get bc/${appBlueName} |grep -v NAME|awk '{print \$1}' > bc.txt"
                        bluebc = readFile('bc.txt').trim()
                        if (bluebc == "${appBlueName}") {
                          echo "Blue BuildConfig already deployed"
                        } else if (bluebc == "") {
                            checkout([$class: "GitSCM", branches: [[name: "*/${gitBranch}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: "RelativeTargetDirectory", relativeTargetDir: "${gitContext}"]], submoduleCfg: [], userRemoteConfigs: [[url: "${gitURL}"]]])
                            sh "oc new-app -f OpenShift/templates/build-template.json -p GIT_REPO_URL=${gitURL} -p GIT_REPO_BRANCH=${gitBranch} -p GIT_COMMIT=${gitCommit} -p GIT_CONTEXT_DIR=${gitContext} -p MICROSERVICE_NAME=${microName} -p APPLICATION_NAME=${appBlueName} -p APPLICATION_ID=${appID} -p BUILD_CPU_REQUEST=${cpuRequest} -p BUILD_CPU_LIMIT=${cpuLimit} -p BUILD_MEM_REQUEST=${memRequest} -p BUILD_MEM_LIMIT=${memLimit} -p VERSION_NUMBER=${version} -n ${project} --dry-run -o yaml | oc apply -f - -n ${project}"
                        }
                      }

                      stage('Create Green-App BuildConfig') {
                        sh "oc get bc/${appGreenName} |grep -v NAME|awk '{print \$1}' > bc.txt"
                        greenbc = readFile('bc.txt').trim()
                        if (greenbc == "${appGreenName}") {
                          echo "Green BuildConfig already deployed"
                        } else if (greenbc == "") {
                            checkout([$class: "GitSCM", branches: [[name: "*/${gitBranch}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: "RelativeTargetDirectory", relativeTargetDir: "${gitContext}"]], submoduleCfg: [], userRemoteConfigs: [[url: "${gitURL}"]]])
                            sh "oc new-app -f OpenShift/templates/build-template.json -p GIT_REPO_URL=${gitURL} -p GIT_REPO_BRANCH=green -p GIT_COMMIT=${gitCommit} -p GIT_CONTEXT_DIR=${gitContext} -p MICROSERVICE_NAME=${microName} -p APPLICATION_NAME=${appGreenName} -p APPLICATION_ID=${appID} -p BUILD_CPU_REQUEST=${cpuRequest} -p BUILD_CPU_LIMIT=${cpuLimit} -p BUILD_MEM_REQUEST=${memRequest} -p BUILD_MEM_LIMIT=${memLimit} -p VERSION_NUMBER=${version} -n ${project} --dry-run -o yaml | oc apply -f - -n ${project}"
                        }
                      }

                      stage('Create Blue-App DeploymentConfig') {
                        sh "oc get dc/${appBlueName} |grep -v NAME|awk '{print \$1}' > dc.txt"
                        bluedc = readFile('dc.txt').trim()
                        if (bluedc == "${appBlueName}") {
                          echo "Blue DeploymentConfig already deployed"
                        } else if (bluedc == "") {
                            checkout([$class: "GitSCM", branches: [[name: "*/${gitBranch}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: "RelativeTargetDirectory", relativeTargetDir: "${gitContext}"]], submoduleCfg: [], userRemoteConfigs: [[url: "${gitURL}"]]])
                            sh "oc new-app -f OpenShift/templates/deploymentconfig-template.json -p GIT_COMMIT=${gitCommit} -p MICROSERVICE_NAME=${microName} -p APPLICATION_NAME=${appBlueName} -p APPLICATION_ID=${appID} -p DEPLOY_CPU_REQUEST=${cpuRequest} -p DEPLOY_CPU_LIMIT=${cpuLimit} -p DEPLOY_MEM_REQUEST=${memRequest} -p DEPLOY_MEM_LIMIT=${memLimit} -p VERSION_NUMBER=${version} -p NUM_REPLICAS=0 -n ${project} --dry-run -o yaml | oc apply -f - -n ${project}"
                        }
                      }

                      stage('Create Green-App DeploymentConfig') {
                        sh "oc get dc/${appGreenName} |grep -v NAME|awk '{print \$1}' > dc.txt"
                        greendc = readFile('dc.txt').trim()
                        if (greendc == "${appGreenName}") {
                          echo "Green DeploymentConfig already deployed"
                        } else if (greendc == "") {
                            checkout([$class: "GitSCM", branches: [[name: "*/${gitBranch}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: "RelativeTargetDirectory", relativeTargetDir: "${gitContext}"]], submoduleCfg: [], userRemoteConfigs: [[url: "${gitURL}"]]])
                            sh "oc new-app -f OpenShift/templates/deploymentconfig-template.json -p GIT_COMMIT=${gitCommit} -p MICROSERVICE_NAME=${microName} -p APPLICATION_NAME=${appGreenName} -p APPLICATION_ID=${appID} -p DEPLOY_CPU_REQUEST=${cpuRequest} -p DEPLOY_CPU_LIMIT=${cpuLimit} -p DEPLOY_MEM_REQUEST=${memRequest} -p DEPLOY_MEM_LIMIT=${memLimit} -p VERSION_NUMBER=${version} -p NUM_REPLICAS=0 -n ${project} --dry-run -o yaml | oc apply -f - -n ${project}"
                        }
                      }

                      stage('Create Application Vanity URL') {
                        sh "oc get route/${appRoute} |egrep -v NAME |awk '{print \$1}' > route.txt"
                        route = readFile('route.txt').trim()
                        if (route == "${appRoute}") {
                          echo "Vanity URL already deployed"
                        } else if (route == "") {
                            sh "oc get route/${appBlueName} -o jsonpath='{ .spec.host }' |cut -f2- -d. > domain.txt"
                            subdomain = readFile('domain.txt').trim()
                            sh "oc expose svc/${appBlueName} --name=${appRoute} --hostname=${appRoute}.${subdomain}"
                        }
                      }

                      stage('Build Blue-App HTTPD Container Image') {
                        userInput = input(message: 'Do you wish to Build/Rebuild?', ok: 'Proceed',
                        parameters: [booleanParam(defaultValue: false,
                        description: 'Ticking YES will start a build',
                        name: 'YES?')])
                        sh "echo ${userInput} > userInput.txt"
                        t = readFile('userInput.txt').trim()
                        if (t == "true") {
                          sh "oc start-build ${appBlueName} |awk '{print \$1}'> result.txt"
                          waitUntil {
                            script {
                              def buildnum = readFile('result.txt').trim()
                              def buildst = sh script: "oc get $buildnum -o jsonpath='{ .status.phase }' > buildst.txt"
                              def r = readFile('buildst.txt').trim()
                              r == "Complete"
                            }
                          }
                        } else if (t == "false") {
                            echo "Skipping"
                        }
                      }

                      stage('Build Green-App HTTPD Container Image') {
                        userInput = input(message: 'Do you wish to Build/Rebuild?', ok: 'Proceed',
                        parameters: [booleanParam(defaultValue: false,
                        description: 'Ticking YES will start a build',
                        name: 'YES?')])
                        sh "echo ${userInput} > userInput.txt"
                        t = readFile('userInput.txt').trim()
                        if (t == "true") {
                          sh "oc start-build ${appGreenName} |awk '{print \$1}'> result.txt"
                          waitUntil {
                            script {
                              def buildnum = readFile('result.txt').trim()
                              def buildst = sh script: "oc get $buildnum -o jsonpath='{ .status.phase }' > buildst.txt"
                              def r = readFile('buildst.txt').trim()
                              r == "Complete"
                            }
                          }
                        } else if (t == "false") {
                            echo "Skipping"
                        }
                      }

                      stage('Determine Active Application Branch') {
                        sh "oc get route/${appRoute} -o jsonpath='{ .spec.to.name }' > activesvc.txt"
                        active = readFile('activesvc.txt').trim()
                        if (active == "${appBlueName}") {
                          dest = "${appGreenName}"
                        } else if (active == "${appGreenName}") {
                            dest = "${appBlueName}"
                        }
                        echo "Active Application Branch: " + active
                        echo "Destination Application Branch: " + dest
                      }

                      stage('Switch Application Branch') {
                        userInput = input(message: 'Do you wish to switch?', ok: 'Proceed',
                        parameters: [booleanParam(defaultValue: false,
                        description: "Ticking YES will switch application from the ${active} branch to the ${dest} branch",
                        name: 'YES?')])
                        sh "echo ${userInput} > userInput.txt"
                        t = readFile('userInput.txt').trim()
                        if (t == "true") {
                          sh 'oc patch route/"' + appRoute + '" -p \'{"spec":{"to":{"name":"' + dest + '"}}}\''
                        } else if (t == "false") {
                            echo "Skipping"
                        }
                      }
                    }
                 }
              } catch (err) {
                 echo "in catch block"
                 echo "Caught: ${err}"
                 currentBuild.result = 'FAILURE'
                 throw err
              }
        type: JenkinsPipeline
      triggers:
        -
          github:
            secret: "${GITHUB_TRIGGER_SECRET}"
          type: GitHub
        -
          generic:
            secret: "${GENERIC_TRIGGER_SECRET}"
          type: Generic
parameters:
  -
    description: "Blue/Green HTTPD example"
    name: GIT_REPO_URL
    required: true
    value: "https://github.com/Freddy-Montero/blue-green-example.git"
  -
    description: "What branch to use from GIT (defaults to main)"
    name: GIT_REPO_BRANCH
    required: true
    value: master
  -
    description: "What commit to use from GIT"
    name: GIT_COMMIT
    required: true
    value: HEAD
  -
    description: "Context directory which gives path from above repository down to its root"
    name: GIT_CONTEXT_DIR
    required: false
    value: ""
  -
    description: "A difficult to guess string encoded as part of the webhook URL.  Not encrypted."
    displayName: "GitHub Webhook Secret"
    from: "[a-zA-Z0-9]{40}"
    generate: expression
    name: GITHUB_SECRET
  -
    description: "A secret string used to configure the Generic webhook."
    displayName: "Generic Webhook Secret,"
    from: "[a-zA-Z0-9]{40}"
    generate: expression
    name: GENERIC_WEBHOOK_SECRET
  -
    description: "Name of the microservice"
    name: MICROSERVICE_NAME
    required: true
    value: blue-green
  -
    description: "Name of the Blue application"
    name: APPLICATION_BLUE_NAME
    required: true
    value: blue-app
  -
    description: "Name of the Green application"
    name: APPLICATION_GREEN_NAME
    required: true
    value: green-app
  -
    description: "ID of the application"
    name: APPLICATION_ID
    required: true
    value: httpd-blue-green
  -
    description: "Main route of the application"
    name: APPLICATION_ROUTE
    required: true
    value: app
  -
    description: "The requested CPU for a build or deployment"
    name: CPU_REQUEST
    required: true
    value: 1000m
  -
    description: "The limit of CPU to allow for a build or deployment"
    name: CPU_LIMIT
    required: true
    value: 1000m
  -
    description: "The requested memory for a build or deployment"
    name: MEM_REQUEST
    required: true
    value: 1536Mi
  -
    description: "The limit of memory to allow for a build or deployment"
    name: MEM_LIMIT
    required: true
    value: 1536Mi
  -
    description: "Version of deployment"
    name: VERSION_NUMBER
    required: true
    value: "1.0"
  -
    description: "Number of containers to scale to, via deploymentconfig"
    name: NUM_REPLICAS
    required: true
    value: "1"
